### ISSUE TITLE
"Project not found."

### ISSUE THREAD

**Issue by Nicc0110** [lyc8503/UptimeFlare#34] opened 2024-05-26 22:14 UTC
I've tried multiple times to **build & deploy**, but I keep getting this error:

```
✘ [ERROR] A request to the Cloudflare API (/accounts/[REDACTED]/pages/projects/uptimeflare) failed.

  Project not found. The specified project name does not match any of your existing projects. [code: 8000007]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/workers-sdk/issues/new/choose
```

Every other step passes, but this one fails.

**Comment by lyc8503** [comment] 2024-05-26 23:23
Hello, if your project configuration doesn't contain sensitive information, could you please set the repository to public temporarily so that I can view more complete log information.

If it is not convenient, could you please find the logs from the Terraform step of your FIRST Action run and see if there are any different error messages and provide me with the error logs. Full error logs would be appreciated.

**Comment by Nicc0110** [comment] 2024-05-27 00:35
It's under an organization, can I add you to the project directly so you can have a look at it. I'd rather not display it to all.

**Comment by lyc8503** [comment] 2024-05-27 00:42
> It's under an organization, can I add you to the project directly so you can have a look at it. I'd rather not display it to all.

That's ok, you can invite me to join the organization. Thank you for your help.

**Comment by Nicc0110** [comment] 2024-05-27 00:45
I do believe I have added you to the repo, please let me know if you need any additional permissions.

**Comment by lyc8503** [comment] 2024-05-27 00:56
Thanks to your help, I can now see the logs. It looks like the problem was caused by a Terraform deployment error, the logs are as below.

```
╷
│ Error: error creating workers kv namespace: create namespace: 'a namespace with this account ID and title already exists' (10014)
│ 
│   with cloudflare_workers_kv_namespace.uptimeflare_kv,
│   on deploy.tf line 19, in resource "cloudflare_workers_kv_namespace" "uptimeflare_kv":
│   19: resource "cloudflare_workers_kv_namespace" "uptimeflare_kv" {
│ 
╵
```

Have you tried deploying this project before, but then recreated the repository? It looks like something is conflicting.

Can you try redeploying it after deleting the relevant resources under your Cloudflare account?

Specifically:
1. Open https://dash.cloudflare.com/redirect?account=workers/kv/namespaces and remove `uptimeflare_kv` (if any)
2. Open https://dash.cloudflare.com/redirect?account=workers-and-pages and remove `uptimeflare` and `uptimeflare_worker` (if any) from there.
3. Update your configuration file to trigger a deployment.

**Comment by Nicc0110** [comment] 2024-05-27 01:05
Yep, that worked. I had not created any other repo, though I ran it 3 times and deleted what I found each time. (Meaning some things might've been gone and some might've stayed). But, you fixed the error, thank you so much for your help. Does that mean in the future whenever I want to update the config I need to delete everything?

**Comment by lyc8503** [comment] 2024-05-27 01:10
It's not quite clear what the cause of the problem might have been, but it should have been fixed by now. You can update the config file as much as you like after that, no worries!

**Comment by Nicc0110** [comment] 2024-05-27 01:11
Okay, thank you again so much for your help.

**Comment by lyc8503** [comment] 2024-05-27 01:12
You're welcome and thank you very much for reporting the problem, I've left your organization and I'll go ahead and close this issue if the problem has been resolved.

**Closed as completed by lyc8503** 2024-05-27 01:12 UTC
Labels: deployment
