### ISSUE TITLE
checkLocationWorkerRoute not working

### ISSUE THREAD

**Issue by SN-Koarashi** [lyc8503/UptimeFlare#75] opened 2024-11-09 09:34 UTC
When I followed the wiki to configure everything, everything was fine until yesterday when it started returning `Error initiating check from remote worker` errors. I checked the worker logs and the following is the log content:
```
    {
      "message": [
        "[SLC] Checking NAS 服務..."
      ],
      "level": "log",
      "timestamp": 1731144213617
    },
    {
      "message": [
        "Calling worker: https://tw-cloudflare.snkms.com/"
      ],
      "level": "log",
      "timestamp": 1731144213617
    },
    {
      "message": [
        "Error calling worker: SyntaxError: Unexpected token 'e', \"error code: 1002\" is not valid JSON"
      ],
      "level": "log",
      "timestamp": 1731144213638
    },
```
`tw-cloudflare` subdomain is recorded through the proxied A to `8.39.126.111`

When I cancel `checkLocationWorkerRoute`, everything works fine except that I cannot use the location-specific functionality.

**Comment by lyc8503** [comment] 2024-11-09 12:37
Hi, error 1002 means `DNS points to a forbidden IP`. It looks like you have chosen an IP address that is not reserved for workers. Perhaps you could try selecting a different IP address. (I'm not quite sure if Cloudflare offers Workers service in Taiwan... If you can't find an available IP, you may need to choose a neighboring region, e.g. Singapore / Japan / Korea)

**Comment by SN-Koarashi** [comment] 2024-11-09 13:21
Actually, I've been using it for about a week, and it just stopped working yesterday. 
According to your suggestion, I switched the IP to the Japanese IP `8.34.201.12` mentioned in the wiki, and it started working.

I don't know why many of the IPs from Taiwan and Hong Kong that I've been testing have become invalid these past few days; it's really strange.

It might be that the IPs from Taiwan and Hong Kong no longer support Worker. I'm not sure; anyway, it works fine with a Japanese IP right now. If there are any issues, I'll reply again.

**Comment by lyc8503** [comment] 2024-11-09 13:31
If it was available before and then suddenly became unavailable, it is possible that Cloudflare has made internal adjustments. In Taiwan and Hong Kong, due to higher bandwidth costs, Cloudflare may not have as many nodes deployed, and is more likely to have had some maintenance or changes. (By the way, there is a plan to improve `checkLocationWorkerRoute` https://github.com/lyc8503/UptimeFlare/issues/55. This should solve the problem of invalid worker addresses caused by these kinds of Cloudflare changes, but it hasn't been implemented yet.)

**Comment by lyc8503** [comment] 2024-11-09 13:31
Closing this for now, feel free to reopen it if the problem reappears.

**Closed as completed by lyc8503** 2024-11-09 13:31 UTC

**Comment by tkjaergaard** [comment] 2024-12-23 10:36
I've tried following the wiki, but I also continuously getting 1002 error (forbidden ip).

I've downloaded a fresh list and gotten the ip's. Have anyone found a way to actually identifying which ip's is usable?

I've tried random ones for Germany. But no luck so far.
